-- Regenerates imgui/imgui_impl_wvk_spirv.inl from imgui/imgui_impl_wvk.hlsl.
--
--     xmake lua imgui/generate_spirv.lua          (run from the wvk root)
--
-- Only needed after editing the shader; the generated header is committed so that the ImGui
-- backend builds without dxc. The dxc lookup matches xmake/rules/hlsl2spv.lua: $DXC, then
-- $VULKAN_SDK/bin, then PATH. The flags also match that rule, in release mode.

import("core.base.bytes")
import("lib.detect.find_program")

local function find_dxc()
    local dxc = os.getenv("DXC")
    if dxc and os.isfile(dxc) then
        return dxc
    end
    local paths = {}
    for _, envname in ipairs({"VULKAN_SDK", "VK_SDK_PATH"}) do
        local sdk = os.getenv(envname)
        if sdk then
            table.insert(paths, path.join(sdk, "bin"))
            table.insert(paths, path.join(sdk, "Bin"))
        end
    end
    return find_program("dxc", {paths = paths})
end

-- Formats a SPIR-V blob as a C array of 32-bit words, eight per line.
local function words_of(file, name)
    local data = bytes(io.readfile(file, {encoding = "binary"}))
    assert(data:size() % 4 == 0, file .. " is not a whole number of 32-bit words")
    local lines = {}
    local line = {}
    for offset = 1, data:size(), 4 do
        local word = data[offset] | (data[offset + 1] << 8) | (data[offset + 2] << 16) | (data[offset + 3] << 24)
        table.insert(line, string.format("0x%08x", word))
        if #line == 8 then
            table.insert(lines, "    " .. table.concat(line, ", ") .. ",")
            line = {}
        end
    end
    if #line > 0 then
        table.insert(lines, "    " .. table.concat(line, ", ") .. ",")
    end
    return string.format("static const uint32_t %s[] = {\n%s\n};\n", name, table.concat(lines, "\n"))
end

function main()
    local root = os.curdir()
    local source = path.join(root, "imgui", "imgui_impl_wvk.hlsl")
    local output = path.join(root, "imgui", "imgui_impl_wvk_spirv.inl")
    if not os.isfile(source) then
        raise("run this from the wvk root: %s not found", source)
    end

    local dxc = find_dxc()
    if not dxc then
        raise("dxc not found. Install the Vulkan SDK, or set DXC to the dxc executable.")
    end

    local tmpdir = os.tmpfile() .. ".dir"
    os.mkdir(tmpdir)

    local common = {
        "-spirv",
        "-fspv-target-env=vulkan1.3",
        "-fspv-entrypoint-name=main",
        "-fvk-use-scalar-layout",
        "-fvk-bind-resource-heap", "0", "0",
        "-fvk-bind-sampler-heap", "1", "0",
        "-O3",
        "-I", root,
    }
    local stages = {
        {entry = "vertex_main", profile = "vs_6_6", name = "imgui_impl_wvk_vertex_spirv"},
        {entry = "pixel_main",  profile = "ps_6_6", name = "imgui_impl_wvk_fragment_spirv"},
    }

    local parts = {
        "// Generated by imgui/generate_spirv.lua from imgui/imgui_impl_wvk.hlsl. Do not edit.\n",
        "// Regenerate with: xmake lua imgui/generate_spirv.lua\n\n",
    }
    for _, stage in ipairs(stages) do
        local spv = path.join(tmpdir, stage.entry .. ".spv")
        os.vrunv(dxc, table.join(common, {"-T", stage.profile, "-E", stage.entry, "-Fo", spv, source}))
        table.insert(parts, words_of(spv, stage.name))
        table.insert(parts, "\n")
    end
    os.rm(tmpdir)

    io.writefile(output, table.concat(parts))
    cprint("${color.success}generated %s", path.relative(output, root))
end
